### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by NordLandeW** [NordLandeW/DyNode#7]
## UI

- [ ] UI 布局重构
  - [ ] 添加设置页面
  - [ ] 添加类似 Dynamaker 的右键选单

## Playback

- [ ] 左右侧闪烁提示
- [x] 暂停横幅
- [ ] Full Combo 动画
- [ ] 进入回放模式的动画
- [x] #41

## Editor

- [ ] 批量选择时间段所有Note
- [x] #44 
- [x] 批量移动/修改Hold末尾
- [ ] 撤销/还原优化
- [ ] 多难度管理
- [ ] 官谱编辑模式

## Themes

- [x] 经典 Dynamix 主题
  - [x] 标题半透明化
  - [x] 更加合适的 Hold 动画
  - [x] 背景 glow 动画曲线修改 & 透明度增大
  - [x] 默认白色背景
  - [x] 更细的判定线
  - [x] 更加还原的粒子效果
  - [x] 更加线性的Combo动画
- [ ] Dynamite 主题
- [x] #61 

## Localization

- [x] 本地化/多语言支持

## Miscs

- [ ] 一键导出背景图 & 难度设置图片
- [ ] Input 重构
- [x] #35
- [ ] 对侧面能放置的音符类型施加限制
- [x] 快捷键速查表 etc

## Performance

- [x] Deactivate 不被画面包含的 Note (0.1.0)
- [x] 加速谱面导入导出速度
  - [x] osz 导入重构
  - [x] xml 导入重构
  - [x] xml 导出重构

**待讨论的内容。**

- [ ] 接管节拍线处理
- [ ] Note 拖拽、放置和删除优化

**Comment by NagaseIori** [comment]
@all-contributors please add @NagaseIori for the project leader, designer and coding.
